### ISSUE TITLE
As an outfitter / guide applicant, I want to be able to learn about the basic restrictions of a temporary (3 year) permit.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#148]
Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested

**Comment by dubharmonic** [comment]
Add a description of what a temp outfitter is somewhere in the application.

**Comment by npage123** [comment]
Add the following text to the end of the temp outfitter permit type description text on the landing page:

"Click here to read more information about temporary outfitter permits."

The following page gives a more in depth explanation of temp outfitter permits and the restrictions at Mt. Baker Snoqualmie Forest. Whether or not to just link to this page or create a newly branded (one that matches the intake prototype) page is up in the air - https://www.fs.usda.gov/detail/mbs/passes-permits/event-commercial/?cid=stelprdb5295496

**Comment by npage123** [comment]
Add the following sentence to the end of the temp outfitter's permit type description:

"To learn more about a temporary outfitter's permit click here."

See screenshot for reference.
<img width="502" alt="screen shot 2017-08-30 at 3 56 06 pm" src="https://user-images.githubusercontent.com/12956624/29895043-39a2b55a-8d9d-11e7-98af-634d3db6396c.png">

The "click here" text will end up linking to a new page that is being mocked up.

**Comment by npage123** [comment]
@thegoldentoilet - Updated content:

Temporary outfitters permit information

Generally, if you charge a fee for someone to participate in a service that you are providing, or if you otherwise stand to gain from providing the service, you need a permit. The value of the public service provided, the amount charged, or the value of the experience had by the participants is not relevant.

See definitions for “Commercial Use”, “Guiding”, “Outfitting”.

Non-profit status is not relevant to whether or not you need a permit. Some of our largest permitted outfitting and guiding organizations are non-profits providing great public benefits.
 
A temporary use permit is

• Authorization to conduct short term outfitted or guided use on national Forest Service land
• Non- renewable
• Non-competitive
• One permit, less or equal to 200 days in a 180 day period per use area
• Based on a flat rate fee schedule
• Held by an outfitter qualified to provide service
• Not based on performance evaluations
• Requires annual use reports to be accepted
• Requires insurance (FSM2713.1 Exhibit 1) to be accepted
• Requires an operating plan to be accepted
• Revocable and suspendable
• Not appealable
 
Applicants

• Applicants must be qualified to provide the proposed service, possessing required state licenses and adequate liability insurance.
• Final determination of qualifications is made on the Mt. Baker-Snoqualmie National Forest.
• Violations of laws, customer complaints and adverse performance and permit compliance will be considered in evaluating qualifications.
 
Number of permits and service days restrictions

Permits and service days are managed by use area. The maximum allowable service days varies by use area depending on their availability and demand. Only one temporary permit may be obtained per use area every 180 days up to the max number of service days per use area (no more than 200 service days). See the various permit pool documents for descriptions of use areas and the max number of service days that may be applied for in each area.

• Example 1: Use area "A" = 1000 total pool days with a max days/permit = 200. I can only apply for 1 permit up to 200 days every 6 months in use area "A".
• Example 2: Use Area "B" = 150 total pool days with a max days/permit = 50. I can only apply for 1 permit up to 50 days every 6 months in use area "B". 
• Example 3: Use Area "A" + "B" = 200 days "A" + 50 days "B" = 250 days "A" and "B".

Note: As shown in example 3 You can apply for days from multiple use areas at the same time.
 
Benefits

• Allows for a short-term allocation of use to meet a seasonal needs
• Provides an opportunity to try new activities/locations
• Adds clients or trips for special events or offerings
• Increases flexibility in locations
• Less time spent processing paperwork
• Opportunities for church, youth and educational groups to obtain short term permits for brief and non-recurring outings
 
Activities and locations

• Land-based outfitting and guide permits are available throughout the forest, at the discretion of District Rangers. 
• River-based guiding permits are currently only available for select locations.

The Forest Service may add, remove or modify the activities and locations at our discretion.
 
Costs

A flat fee is charged for a fixed amount of use however, there may be additional costs based on your activity.
 
Number of service days                       Flat fee	                                  Maximum gross revenue for each 
												    bracket of service days
1 to 50						 $150				   $10,000
51 to 100						 $300				   $20,000
101 to 150					 $450				   $30,000
151 to 200					 $600				   $40,000
(See FSH 2709.11, sec. 37.21c)

Application due dates

Administration of the temporary permits varies by pool and is specified in the lands or river pool permit documents.

Ideally there would be plenty of days available to allow all temp permits to be issued on a first come first served basis. However some permit pools are limited and with high demand and there simply are not enough days to go around. For pools such as this we will allocate the permits by a lottery and a due date is needed to make that work. The due dates are months ahead of the permit period so that applicants who get drawn for a permit will have plenty of lead time to advertise and prepare for the trips. In the event that there are unallocated days left over after the lottery, additional permits may be issued on a first come first served basis.
 
Permits for other forests

Forest Service regulations allow for, but do not require, the administration of temporary permit pools. Inquiries on permitting on other forests should be directed to those forests. Information for National Forests within the United States can be found here.

More information on Forest Service outfitter/guide policies and regulations

Visit the national website.

**Comment by dubharmonic** [comment]
Feedback:
* The link might be too subtle
