### ISSUE TITLE
For noncommercial permit, the form field validation alerts do not announce properly in IE11 or Chrome

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#517]
For noncommercial permit, the form field validation alerts do not announce properly in IE11 or Chrome. As the user tabs to a new field and leaves the previously required field blank, an alert is displayed and should be announced that the previous field was required. In Firefox these alerts are displayed and announced. In IE11 and Chrome they are not announced by the screen reader.

http://www.w3.org/TR/WCAG20-TECHS/ARIA19.html

![image](https://user-images.githubusercontent.com/28604890/27606636-15e2f862-5b4f-11e7-8f4b-caffde19bd52.png)

WCAG: 3.3 Input Assistance - 3.3.1 Error Identification 
S-508: 1194.21 (l) 
LINK: EPERM-55

**Comment by sethalt** [comment]
@JohnHewittCriterion would adding the aria-required="true" to those required fields so that 'required' is announced when a user focus' on the field sufficiently solve this issue? One solve for this is using the `aria-live` tag to listen for alerts and announce them.  In doing some research, I've read that using the aria-live tag can be disruptive (bottom of this page: https://www.paciellogroup.com/blog/2014/03/screen-reader-support-aria-live-regions/).  Please advise. Thank you!
