### ISSUE TITLE
As an admin, I can understand clearly which applications need my attention.

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#696]
In the sprint 8 demo Colin mentioned that it would be a good idea to revisit this design and potentially simplify the interface.

Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities 
- [x] Flexion code review
- [x] Documentation / readme.md updated
- [x] Docker updated
- [x] Visual design review
- [x] Usability tested
- [x] Deployed to staging

**Comment by npage123** [comment]
Use following mockup for reference - https://github.com/flexion/fs-intake-module/commit/e4110a7120ef6730ccc9530e99122dda11ac3de3

Functionality summary:
The "Date Submitted" column heading changes to "Submitted" column heading. When applications are received, their submitted text would read from 1 to 48 hours with 48 hour old permits listed in hierarchy over any < 48 hours. Text to read for example "48 hours ago". If a permit has been submitted over 48 hours ago, the text would show the date submitted rather than the hours and be bold and in red. 

If an application is on hold, its start date column would show the date and time currently. If the date and time goes below 1 week, it should then show the number of days left, for example "In 7 days". If the current date is the current start date or after, the start date would turn back to the date and be in bold and red. Same for end date if applies.

**Comment by sethalt** [comment]
@npage123 please review this page and confirm that it has been completed to your specifications.

**Comment by npage123** [comment]
@sethalt - Would it be possible to take off the periods in the submitted, start dates and end dates?

**Comment by npage123** [comment]
@dubharmonic - An addition in the START DATE and END DATE columns' functionality. When the start date and end date is a week away, show in bold red font please. When start date has expired, the thought is that it would not show in this view anymore but go to say and expired applications list (yet to be determined how to view those).

**Comment by dubharmonic** [comment]
Can we change the red to a less chaotic color?

**Comment by dubharmonic** [comment]
Before we do usability testing we should update the test data to be more realistic.
