### ISSUE TITLE
TODO List scrolls over header on bad input data

### ISSUE THREAD

**Issue by JohnHewittCriterion** [flexion/fs-intake-module#786]
When submitting missing or other failed input data the TODO list to the right scrolls over the header.

![image](https://user-images.githubusercontent.com/28604890/29584058-8a412ee0-8750-11e7-82f8-3ab781ef12da.png)

**Comment by thegoldentoilet** [comment]
After you scroll all the way down to the bottom of the form, the place marker is still highlighting step 9. Sometimes, this is because a part of step 9 is still showing. The plugin ng-in-viewport returns an array of inputs sections that are currently in viewport. In this scenario, there are two indexes in the array, and we are choosing the 0 index. This causes the highlight to stay on step 9 sometimes. 

There also is an inconsistent small problem at certain screen heights where the todo list will flash in place, and then disappear after you have scrolled all the way down. The list reappears when you scroll up to step 9. 

Both of these problems are intermittent and only occur in certain screen sizes that I haven't been able to pin down yet.

**Comment by JohnHewittCriterion** [comment]
I primarily test on a 2560 x 1440 resolution if that helps.

**Comment by sethalt** [comment]
-[x] tested on IE
