### ISSUE TITLE
As an applicant, I receive an email when my application is put on hold telling me I should log back in and update my application.

### ISSUE THREAD

**Issue by colinpmacarthur** [flexion/fs-intake-module#844]
Tasks

- [x] Create email text (Nate)
- [x] Add email to server (Seth)

Definition of Done

 - [x] Code unit / e2e tested and comply with QWASP
 - [x] No new security vulnerabilities
 - [x] Flexion code review
 - [x] Documentation / readme.md / CircleCI updated
 - [x] Docker updated
 - [ ] Compare finished design with mockup
 - [ ] Usability tested

**Comment by npage123** [comment]
Proposed noncommercial application hold email text:

SUBJECT LINE: An update on your recent permit application to the Forest Service.

Permit application status update
*********************************

Your recently submitted application has been put on hold due to insufficient information. Please log in, provide the requested information below, and save your application.

[Hold message]

Login at https://idp.int.login.gov/sign_up/start?request_id=929839f8-cd9e-4f7f-9bc1-2f6845999e0c

Application details
*********************************

Event name: 
Start date: 
End date: 
Number of participants: 
Number of spectators: 
Location: 


What happens next?
*********************************

1. Your new information will be reviewed by our staff.
2. If additional information is needed, a representative of the National Forest Service will contact you via email to resolve any issues.
3. Once your application has been reviewed by our staff, you will be notified of the application status.
4. If your application is approved, you will receive your permit within 2 weeks of approval.


Contact us
*********************************

If you have questions or need to contact the permit staff at the National Forest Service, please use a method listed below.

Noncommercial contact


Name: Sue Sherman-Biery
Title: Special use administrator
Phone: 360-854-2660
Email: sshermanbiery@fs.fed.us


Thank you for your interest in our National Forests.
